name: ExpandedBans
version: '0.1'
main: pl.olafcio.expandedbans.ExpandedBans
api-version: '1.21'
load: STARTUP
authors: [Olafcio]
description: The most feature-rich free punishment plugin.
website: https://olafcio1.github.io
softdepend:
  - ProtocolExtension
  - PlaceholderAPI
libraries:
  - org.xerial:sqlite-jdbc:3.51.1.0
commands:
  expandedbans:
    description: The main plugin command.
  xban:
    description: Bans a player.
    permission: expandedbans.ban
    aliases: [ban]
  xbanip:
    description: Bans an IP address. Can be provided a player to get its IP.
    permission: expandedbans.banip
    aliases: [banip]
  xtempban:
    description: Temporarily bans a player.
    permission: expandedbans.tempban
    aliases: [tempban]
  xtempbanip:
    description: Temporarily bans an IP address. Can be provided a player to get its IP.
    permission: expandedbans.tempbanip
    aliases: [tempbanip]
  xunban:
    description: Unbans a player.
    permission: expandedbans.unban
    aliases: [unban]
  xunbanip:
    description: Unbans an IP address. Can be provided a player to get its IP.
    permission: expandedbans.unbanip
    aliases: [unbanip]
  xbanclear:
    description: Unbans all players and IP addresses.
    permission: expandedbans.banclear
    aliases: [banclear]
  xkick:
    description: Kicks a player.
    permission: expandedbans.kick
    aliases: [kick]
  xkickall:
    description: Kicks all players.
    permission: expandedbans.kickall
    aliases: [kickall]
  xmute:
    description: Mutes a player.
    permission: expandedbans.mute
    aliases: [mute]
  xmuteip:
    description: Mutes an IP address. Can be provided a player to get its IP.
    permission: expandedbans.muteip
    aliases: [muteip]
  xtempmute:
    description: Temporarily mutes a player.
    permission: expandedbans.tempmute
    aliases: [tempmute]
  xtempmuteip:
    description: Temporarily mutes an IP address. Can be provided a player to get its IP.
    permission: expandedbans.tempmuteip
    aliases: [tempmuteip]
  xunmute:
    description: Unmutes a player.
    permission: expandedbans.unmute
    aliases: [unmute]
  xunmuteip:
    description: Unmutes an IP address. Can be provided a player to get its IP.
    permission: expandedbans.unmuteip
    aliases: [unmuteip]
  xmuteclear:
    description: Unmutes all players and IP addresses.
    permission: expandedbans.muteclear
    aliases: [muteclear]
  xwarn:
    description: Warns a player.
    permission: expandedbans.warn
    aliases: [warn]
  xwarnip:
    description: Warns an IP address. Can be provided a player to get its IP.
    permission: expandedbans.warnip
    aliases: [warnip]
  xtempwarn:
    description: Temporarily warns a player.
    permission: expandedbans.tempwarn
    aliases: [tempwarn]
  xtempwarnip:
    description: Temporarily warns an IP address. Can be provided a player to get its IP.
    permission: expandedbans.tempwarnip
    aliases: [tempwarnip]
  xunwarn:
    description: Removes a warning of the specified ID or a player's last warning.
    permission: expandedbans.unwarn
    aliases: [unwarn]
  xunwarnip:
    description: Removes a warning of the specified ID or an IP address's last warning.
    permission: expandedbans.unwarnip
    aliases: [unwarnip]
  xwarnclear:
    description: Unwarns all players and IP addresses.
    permission: expandedbans.warnclear
    aliases: [warnclear]
  xnote:
    description: Adds a note to a player.
    permission: expandedbans.note
    aliases: [note]
  xnoteip:
    description: Adds a note to an IP address. Can be provided a player to get its IP.
    permission: expandedbans.noteip
    aliases: [noteip]
  xnotes:
    description: Gets notes about a player.
    permission: expandedbans.notes
    aliases: [notes]
  xnotesip:
    description: Gets notes about an IP address. Can be provided a player to get its IP.
    permission: expandedbans.notesip
    aliases: [notesip]
  xunnote:
    description: Removes a note with the given ID.
    permission: expandedbans.unnote
    aliases: [unnote]
  xnoteclear:
    description: Clears all notes of a player.
    permission: expandedbans.noteclear
    aliases: [noteclear]
  xnoteipclear:
    description: Clears all notes of an IP address.
    permission: expandedbans.notesipclear
    aliases: [noteipclear]
  xalts:
    description: Gets a player's alt list.
    permission: expandedbans.alts
    aliases: [alts]
  xfreeze:
    description: Freezes a player.
    permission: expandedbans.freeze
    aliases: [freeze]
  xunfreeze:
    description: Unfreezes a player.
    permission: expandedbans.unfreeze
    aliases: [unfreeze]
  xlockchat:
    description: Locks the chat.
    permission: expandedbans.lockchat
    aliases: [lockchat]
  xunlockchat:
    description: Unlocks the chat.
    permission: expandedbans.unlockchat
    aliases: [unlockchat]
  xlockdown:
    description: Locks the server down.
    permission: expandedbans.lockdown
    aliases: [lockdown]
  xunlockdown:
    descriptions: Removes the server lockdown.
    permission: expandedbans.unlockdown
    aliases: [unlockdown]
  xwhois:
    description: Gets information about a player.
    permission: expandedbans.whois
    aliases: [whois]
  xhistory:
    description: Gets punishment history of a player.
    permission: expandedbans.history
    aliases: [history]
  xbanlist:
    description: Gets ban history of a player or an IP address.
    permission: expandedbans.banlist
    aliases: [banlist]
  xmutelist:
    description: Gets mute history of a player or an IP address.
    permission: expandedbans.mutelist
    aliases: [mutelist]
  xwarnlist:
    description: Gets warn history of a player or an IP address.
    permission: expandedbans.warnlist
    aliases: [warnlist]
permissions:
  expandedbans.ban:
    default: op
  expandedbans.banip:
    default: op
  expandedbans.tempban:
    default: op
  expandedbans.tempbanip:
    default: op
  expandedbans.unban:
    default: op
  expandedbans.unbanip:
    default: op
  expandedbans.banclear:
    default: op
  expandedbans.kick:
    default: op
  expandedbans.kickall:
    default: op
  expandedbans.mute:
    default: op
  expandedbans.muteip:
    default: op
  expandedbans.tempmute:
    default: op
  expandedbans.tempmuteip:
    default: op
  expandedbans.unmute:
    default: op
  expandedbans.unmuteip:
    default: op
  expandedbans.muteclear:
    default: op
  expandedbans.warn:
    default: op
  expandedbans.warnip:
    default: op
  expandedbans.tempwarn:
    default: op
  expandedbans.tempwarnip:
    default: op
  expandedbans.unwarn:
    default: op
  expandedbans.unwarnip:
    default: op
  expandedbans.warnclear:
    default: op
  expandedbans.note:
    default: op
  expandedbans.noteip:
    default: op
  expandedbans.notes:
    default: op
  expandedbans.notesip:
    default: op
  expandedbans.unnote:
    default: op
  expandedbans.noteclear:
    default: op
  expandedbans.notesipclear:
    default: op
  expandedbans.alts:
    default: op
  expandedbans.freeze:
    default: op
  expandedbans.unfreeze:
    default: op
  expandedbans.lockchat:
    default: op
  expandedbans.lockchat-bypass:
    default: op
  expandedbans.unlockchat:
    default: op
  expandedbans.lockdown:
    default: op
  expandedbans.unlockdown:
    default: op
  expandedbans.whois:
    default: op
  expandedbans.history:
    default: op
  expandedbans.banlist:
    default: op
  expandedbans.mutelist:
    default: op
  expandedbans.warnlist:
    default: op
