allow-command-blocks: false
enabled-commands:
  ##########################################
  ### This section allows you to disable ###
  ### certain ExpandedBans commands for  ###
  ### everyone.                          ###
  ### ---------------------------------- ###
  ### NOTE: Works only on Paper!         ###
  ##########################################

  - xban
  - xbanip
  - xtempban
  - xtempbanip
  - xunban
  - xunbanip
  - xbanclear
  - xkick
  - xkickip
  - xkickall
  - xmute
  - xmuteip
  - xtempmute
  - xtempmuteip
  - xunmute
  - xunmuteip
  - xmuteclear
  - xwarn
  - xwarnip
  - xtempwarn
  - xtempwarnip
  - xunwarn
  - xunwarnip
  - xwarnclear
  - xnote
  - xnoteip
  - xnotes
  - xnotesip
  - xunnote
  - xnoteclear
  - xnoteipclear
  - xalts
  - xfreeze
  - xunfreeze
  - xlockchat
  - xunlockchat
  - xlockdown
  - xunlockdown
  - xwhois
  - xhistory
  - xbanlist
  - xmutelist
  - xwarnlist
chat-commands:
  ##########################################
  ### This section allows you to disable ###
  ### specific server commands for muted ###
  ### players.                           ###
  ##########################################

  # Unprefixed
  - w
  - me
  - tm
  - msg
  - say
  - tell
  - whisper
  - teammsg
  # Minecraft
  - minecraft:w
  - minecraft:me
  - minecraft:tm
  - minecraft:msg
  - minecraft:say
  - minecraft:tell
  - minecraft:teammsg
  # Essentials
  - ew
  - eme
  - emsg
  - esay
  - etell
  - ewhisper
  - essentials:w
  - essentials:me
  - essentials:msg
  - essentials:say
  - essentials:tell
  - essentials:whisper
  - essentials:ew
  - essentials:eme
  - essentials:emsg
  - essentials:esay
  - essentials:etell
  - essentials:ewhisper
